name: Release .pex

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10.5'
          architecture: 'x64'
      - name: Build .pex binary
        run: |
          cd $GITHUB_WORKSPACE
          ./pleasew build --profile ci //:pyllemi-py39 //:pyllemi-py310
          cp plz-out/bin/pyllemi-*.pex ./
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pyllemi-py39.pex
            pyllemi-py310.pex
